build_script:
  - powershell "($WebClient = New-Object System.Net.WebClient).DownloadFile('https://ci.appveyor.com/api/projects/kode54/vgmstream/artifacts/Release/test.zip', 'vgmstream.zip')"
  - powershell "($WebClient = New-Object System.Net.WebClient).DownloadFile('https://ci.appveyor.com/api/projects/Thealexbarney/VGAudio/artifacts/VGAudioCli.exe', 'vgaudio.exe')"
  - powershell "($WebClient = New-Object System.Net.WebClient).DownloadFile('http://www.rarewares.org/files/ogg/oggenc2.88-1.3.5-generic.zip', 'oggenc.zip')"
  - ren 7za 7za.exe
  - 7z x "vgmstream.zip" -y
  - ren test.exe vgmstream.exe
  - 7z x "oggenc.zip" -y
  - ren oggenc2.exe oggenc.exe
  - if not exist mcinput mkdir mcinput
  - if not exist mcoutput mkdir mcoutput
  - del vgmstream.zip
  - del oggenc.zip
  - del COPYING
  - del README.md
  - del in_vgmstream.dll
  - del xmp-vgmstream.dll
  - del ffmpeg.url
  - del .git /Q
  - del "~SETUP.bat"
  - del "appveyor.yml"
  
after_build:
  - 7z a StreamTool_%APPVEYOR_BUILD_VERSION%.zip *
  
artifacts:
  - path: StreamTool_%APPVEYOR_BUILD_VERSION%.zip